name: Semantic Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Or 3.12

      - name: Install python-semantic-release
        run: pip install "python-semantic-release[github]"

      - name: Run semantic-release
        run: semantic-release version --push --no-ci --verbose
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Opcional: Publish to PyPI
      # - name: Build & publish
      #   if: success()  # Or another condition to ensure this runs only on successful release
      #   run: |
      #     pip install build twine
      #     python -m build
      #     twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}